spring.application.name=config.server
server.port=8888
spring.cloud.config.server.git.uri=${CONFIG_REPO_URI:https://github.com/ZedKaS/config-repo.git}
spring.cloud.config.server.git.default-label=${CONFIG_REPO_BRANCH:main}
spring.cloud.config.server.git.basedir=${CONFIG_GIT_BASEDIR:${java.io.tmpdir}/config-repo-cache}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.native.search-locations=${CONFIG_NATIVE_SEARCH_LOCATIONS:file:./config-repo}
management.endpoints.web.exposure.include=health,info
